### ISSUE TITLE
[BUG]:[Tests running on Microsoft Playwright service are inconsistent and failing]

### ISSUE THREAD

**Issue by RF2023** [microsoft/playwright-testing-service#103]
**Describe the bug**
Tests running on Microsoft Playwright service are inconsistent. Same tests have better pass rate via localhost and our non prod env vs running on playwright service.

**To Reproduce**
N/A

**Expected behavior**
Less errors and pass rate should match our local env runs with less time

**Screenshots**

**Setup information (please complete the following information):**
 - Azure Subscription Id:798f112d-0c47-431d-9b57-eeae586eb023
 - Workspace Name: Playwright
 - Service trace Id (if available):
 - Log snippet (if available):
 - Browser on which tests are executed (if applicable): chromium
 - Time range (in PST) when the issue was experienced: Multiple times
 - Playwright Version: 1.42.1
- Client machine OS: MAC
- OS requested on Service: linux

**Additional context**
We have implemented playwright service for few tests, especially when a Pull request is open it runs on 10 workers for 25 tests and once the Pull request is merged it runs on 10 workers for 40 tests and the pass rate is not 100% and throws errors as shown above. We have observed some discrepancies on the results running on the service vs the tests without the service and only on 4 workers (100% pass rate). Couple of tests we have identified that backend was sending data but it was not able to read the data being sent and the UI verification fails.

We tried running 25 tests across 10 workers across 5 instances in parallel and only 3 of them passed with 40-0 and the other two never finished.

Another thing to note is we have few tests which need to run in serial mode, due to the nature of file upload and other scenarios and one test fails in that all of them get skipped.

```TimeoutError: browserType.connect: Timeout 30000ms exceeded.
Call log:
  - <ws connecting> wss://eastus.api.playwright.microsoft.com/api/authorize/connectSession
  - <ws error> wss://eastus.api.playwright.microsoft.com/api/authorize/connectSession error WebSocket was closed before the connection was established
  - <ws connect error> wss://eastus.api.playwright.microsoft.com/api/authorize/connectSession WebSocket was closed before the connection was established
  - <ws disconnected> wss://eastus.api.playwright.microsoft.com/api/authorize/connectSession code=1006 reason=
  - <ws connecting> wss://browser.playwright.microsoft.com/ws
```

AB#2017175

**Comment by RF2023** [comment]
Thanks for responding back to us, so if i understood correctly and lets take this example. When we open a PR we have 25 tests that will run on playwright service on 10 workers. So the consumption is only 10 correct?
Similarly when we merge the PR its 10 workers against 40 tests . The data you shared with us is true for those instances because we did 5 parallel runs and that was total of 50 workers for 125 tests. Did i understand that correctly?

**Comment by RF2023** [comment]
Timeout is set at default 30000

**Comment by RF2023** [comment]
so the 50 workers was a test, we can ignore that we want to go in depth for the one with 10 workers with 30 tests and 40 tests and why there is a discrepancy with our local runs.

**Comment by RF2023** [comment]
sounds good.

**Comment by RF2023** [comment]
8541740441-2-b4bed07479969177b44f6cf6b5f7227c1d19e986
The test run history doesnt allow us to expand a particular run, is there any other place we can see the logs or results?

**Comment by puagarwa** [comment]
> 8541740441-2-b4bed07479969177b44f6cf6b5f7227c1d19e986 The test run history doesnt allow us to expand a particular run, is there any other place we can see the logs or results?

The test run history is not clickable as it only contain few metadata information around run duration and max worker. You would already have all logs at your client side itself. We dont store any logs at server side.

**Comment by puagarwa** [comment]
HI @RF2023
   I checked our telemetry and i can confirm that in last 4 runs, i dont see any failures as load is within quota. Let me know if you see any issue at your side.

**Comment by miguelofbc** [comment]
Hello @puagarwa ! 

Thank you for your previous assistance. We're following up on our discussion about worker quotas.

We recently ran a test suite with the following configuration:
- 5 runs in parallel
- 30 tests per run
- 10 workers per run (total of 50 workers)

We ensured nothing else was running concurrently. Based on our understanding, this setup would require a quota of 50 workers, is that correct?

For reference, here are the run IDs:
1. 8550393480-1-32a7cf53994942134c02b0dfa95005756dc13110
2. 8550393116-1-32a7cf53994942134c02b0dfa95005756dc13110
3. 8550394120-1-32a7cf53994942134c02b0dfa95005756dc13110
4. 8550393820-1-32a7cf53994942134c02b0dfa95005756dc13110
5. 8550394373-1-32a7cf53994942134c02b0dfa95005756dc13110

Nevertheless we still have 2 runs with 1 failure each:

1. Error: locator.fill: Target page, context or browser has been closed [[ SessionID: 3f3601c0-6aa9-4ccd-aa57-b8f3afc07ebd ]]
2. Error: locator.fill: Test timeout of 180000ms exceeded. [[ SessionID: 9110dfc8-f36a-4532-9344-d0513a2daef9 ]]

However, we encountered failures in two of the runs:
- Error: locator.fill: Target page, context or browser has been closed (SessionID: 3f3601c0-6aa9-4ccd-aa57-b8f3afc07ebd)
- Error: locator.fill: Test timeout of 180000ms exceeded (SessionID: 9110dfc8-f36a-4532-9344-d0513a2daef9)

Interestingly, when we run the same tests with this configuration on our own infrastructure, everything works as expected. This suggests the tests themselves might not be flaky.

Would you be able to share your insights on these failures and confirm the required worker quota for our scenario?

**Comment by miguelofbc** [comment]
Hello @puagarwa.

I apologize if my previous message caused any confusion.

To clarify, when I mentioned "our own infrastructure," I meant our CI environment, not local machines. We are running tests in parallel on our CI system, not locally.

W'd appreciate it if you could confirm which failures in our previous message indicate exceeding the worker quota. Are these failures communicated to users in any way?

The specific error we encountered was a TimeoutError: browserType.connect.  Is this the expected error when the quota limit is reached?

Timeout Error Details:

```TimeoutError: browserType.connect: Timeout 30000ms exceeded.
Call log:
  - <ws connecting> wss://eastus.api.playwright.microsoft.com/api/authorize/connectSession
  - <ws error> wss://eastus.api.playwright.microsoft.com/api/authorize/connectSession error WebSocket was closed before the connection was established
  - <ws connect error> wss://eastus.api.playwright.microsoft.com/api/authorize/connectSession WebSocket was closed before the connection was established
  - <ws disconnected> wss://eastus.api.playwright.microsoft.com/api/authorize/connectSession code=1006 reason=
  - <ws connecting> wss://browser.playwright.microsoft.com/ws
```

And we did look into the trace file.

**Here's the key point:** 
We experience flakiness with Playwright service during parallel runs (5 runs) that doesn't occur in our existing CI environment. Even though these failures might be happening during the test phase, due to quota, etc., these tests have been running under similar load for months without issues. Our goal is to adopt Playwright service, but we need to ensure reliability at least matches our current infrastructure.

Would it be helpful if I provided additional logs from the failing runs?

**Comment by puagarwa** [comment]
Hi @miguelofbc ,
     If you hit quota error, you would get timeout error like below or 409 error immediately. so its easy to identify if its quota issue or any other issue during the test phase. 
> TimeoutError: browserType.connect

I understood that you are running it from CI, but i was referring to this line
> Same tests have better pass rate via localhost and our non prod env vs running on playwright service.

I like to confirm here when you are comparing with service vs without service runs, is your testing endpoint same ? My assumption from above line was that you were earlier running with localhost endpoint but with service you have shifted to prod endpoint. So in order to have fair comparison , i advise to use same test endpoint with non-service run and check.


But irrespective of it, We can work on failures we are getting with service and try to understand it. Can you run few times and share failure details. We can understand if there is pattern like particular set of tests prone to failure or particular type of failure.

Few suggestion, i can provide in general
- With service since it works on client-service model, individual tests time could increase due to network hop but the idea is with more parallel workers, it get compensated to keep overall time low.
- You may wants to increase some timeouts in your tests for the above reason if you are hitting those.
- For trace and videos, please keep it 'retain-on-failure' instead of 'on'
- You could enable retry for one off failures.

**Comment by puagarwa** [comment]
HI @miguelofbc ,
Regarding test failure analysis: 
The reason for asking to perform more test run is to find out pattern of failure. in last run you shared two failure, out of that one seems to service related which we trying to understand more. I want to understand if its happening regularly or one off instance. and we are also looking into more detail at our end as well. You can as well look into already ran instances to check for failed test. You can leave out browser.connect timeout failures but we can look into others if any to find pattern. 

Regarding client-service model:
Your tests script creates a websocket connection with our service browser and then send out command to perform browser operations and receive response to execute tests. Unlike when you run without service, there is no websocket connection but test script is passing command to local browser in same machine, hence due to network getting involved in service mode, its expected to see higher test time if you compare for individual tests for with service vs without service. But the benefit of service is it allows you to use higher parallelism which eventually reduce overall test run time.

**Comment by RF2023** [comment]
Here are more runs, please let me know if you need anything else. Thank you !!

8565671485-1-0d2bec4b4e4fdd8af2ea1acb0f977a87e9b743ce
8565671572-1-0d2bec4b4e4fdd8af2ea1acb0f977a87e9b743ce
8565671675-1-0d2bec4b4e4fdd8af2ea1acb0f977a87e9b743ce
8565671794-1-0d2bec4b4e4fdd8af2ea1acb0f977a87e9b743ce
8565671900-1-0d2bec4b4e4fdd8af2ea1acb0f977a87e9b743ce

**Comment by miguelofbc** [comment]
Hello @puagarwa,

We've tried again and here is the report.

Configuration:
- against localhost under CI using ms pw service config
- 5 runs in parallel
- 30 tests per run
- 10 workers per run (total of 50 workers)


Run IDs:
- 8565671485-1-0d2bec4b4e4fdd8af2ea1acb0f977a87e9b743ce
  - 1 failure -> Error: browserType.connect: Target page, context or browser has been closed
- 8565671572-1-0d2bec4b4e4fdd8af2ea1acb0f977a87e9b743ce
- 8565671675-1-0d2bec4b4e4fdd8af2ea1acb0f977a87e9b743ce
  - 3 failures -> Error: browserType.connect: Target page, context or browser has been closed
- 8565671794-1-0d2bec4b4e4fdd8af2ea1acb0f977a87e9b743ce
- 8565671900-1-0d2bec4b4e4fdd8af2ea1acb0f977a87e9b743ce
  - 1 failure -> Error: browserType.connect: Target page, context or browser has been closed

**Comment by RF2023** [comment]
Just to add back to back runs have failed with the following error: Time stamp 12:53 PM EST
Error: browserType.connect: Target page, context or browser has been closed

**Comment by puagarwa** [comment]
Hi @RF2023, @miguelofbc ,
  Thanks for the detail, Let me check and get back. Meanwhile, if you have handy please share sessionId, that would be helpful in debugging.

**Comment by miguelofbc** [comment]
> Hi @RF2023, @miguelofbc ,
> 
>   Thanks for the detail, Let me check and get back. Meanwhile, if you have handy please share sessionId, that would be helpful in debugging.

Sorry, but this time couldn't find that in the report. Is there any other way to get the session ID on our end?

**Comment by puagarwa** [comment]
HI @miguelofbc 
   No issue, i found the issue.

This was related one issue which happen today in our infra, We have fixed it now. It shouldnt happen again. Sorry for the inconvenience.

**Comment by RF2023** [comment]
Our last few runs have been stable, thanks for making the fix. Over the course of last few runs we observed only one failure.

sessionID 291b6586-6aa2-43b3-bd43-c87a68ac6882

error: Test timeout of 180000ms exceeded.

**Comment by miguelofbc** [comment]
Hello @puagarwa ! 
Another failure: `Error: locator.fill: Target page, context or browser has been closed`

SessionId = 7d374527-ba2f-4c59-87d6-26f52c294db0

**Comment by puagarwa** [comment]
> Test timeout of 180000ms exceeded

This is due to our infra machine getting restarted. Usually, this failure should be very rare but we will check to make sure they shouldn't be frequent.

One thing, is it possible for you to add retry in your test suite to counter for these occasional failures and keep your build green.

**Comment by puagarwa** [comment]
Let me bucketize the issues we faced so far and possible solution.

- error: Test timeout of 180000ms exceeded. : This is most likely test issue where test couldnt get completed in 3mins, i will suggest you to check trace to understand where it took more time. if you think its genuinely can take more than 3mins, then increase test timeout. 
- Error: locator.fill: Target page, context or browser has been closed : This is our rare infra issue where machine get restarted due to maintenance and hence test connection drops and test fails. Unfortunately, not much can be done here but retry.
- Error: browserType.connect: Target page, context or browser has been closed : This was our temporary infra issue which shouldnt happen again after our fix.
- browserType.connect: Timeout 30000 , this was due to throttling which you you faced initial when ran more than 50 parallel worker. We could increase [timeout](https://github.com/microsoft/playwright-testing-service/blob/main/samples/get-started/playwright.service.config.ts#L50) but best is to make sure parallel worker should be less than 50 or raise request to increase quota.

**Comment by RF2023** [comment]
> Let me bucketize the issues we faced so far and possible solution.
> 
> * error: Test timeout of 180000ms exceeded. : This is most likely test issue where test couldnt get completed in 3mins, i will suggest you to check trace to understand where it took more time. if you think its genuinely can take more than 3mins, then increase test timeout.
> * Error: locator.fill: Target page, context or browser has been closed : This is our rare infra issue where machine get restarted due to maintenance and hence test connection drops and test fails. Unfortunately, not much can be done here but retry.
> * Error: browserType.connect: Target page, context or browser has been closed : This was our temporary infra issue which shouldnt happen again after our fix.
> * browserType.connect: Timeout 30000 , this was due to throttling which you you faced initial when ran more than 50 parallel worker. We could increase [timeout](https://github.com/microsoft/playwright-testing-service/blob/main/samples/get-started/playwright.service.config.ts#L50) but best is to make sure parallel worker should be less than 50 or raise request to increase quota.

Thank you for the detailed explanation and fixing the infra issue helping us to be more stable. We will look into the time for the test running as we have few runs planned today and tomorrow. Will keep you posted on how it goes. Appreciate it !

**Comment by vvs11** [comment]
Hi @RF2023 
I wanted to check in with you about the stability of your tests. Are you seeing improvements?

**Comment by RF2023** [comment]
Hello, in our last run we are seeing tests failing which have to run serially and we observed it before as well. Can you please take a look at the last three runs and see any discrepancies from your side.

**Comment by puagarwa** [comment]
Hi @RF2023 We are looking into these runs. BTW can you share what error did your test gave during failure. We need to understand if this is due to service issue or something went wrong at client side. If possible share error log and sessionId if possible.

**Comment by puagarwa** [comment]
HI @RF2023
    Thanks for sharing details. We looked into these sessions and below are finding
- for "Error: browserType.connect: Timeout 30000ms exceeded" : This is our infra issue.
- for "Test timeout of 180000ms exceeded": In this case, out telemetry shows test session was fine and then it got closed after sometime without any activity. we should check trace or video to understand what happened in this case. this could be due to test issue or test endpoint issue.

**Comment by miguelofbc** [comment]
@puagarwa could you please elaborate on what is the issue and if that is being taken care?
> for "Error: browserType.connect: Timeout 30000ms exceeded" : This is our infra issue.

**Comment by puagarwa** [comment]
> @puagarwa could you please elaborate on what is the issue and if that is being taken care?
> 
> > for "Error: browserType.connect: Timeout 30000ms exceeded" : This is our infra issue.

This is due to underlying browser got into bad state during the connection time and hence we couldnt connect your request. Ideally, this should be rare but we are planning a long term fix for it this month which should take care of it.

**Comment by RF2023** [comment]
@puagarwa do you have an update on when it will be released??

**Comment by puagarwa** [comment]
> @puagarwa do you have an update on when it will be released??

Hi @RF2023, It is currently in our backlog with no confirmed date of release. We are also monitoring telemetry to understand its frequency and accordingly bump up priority. Please let us know if you are facing it with more frequency.

**Comment by RF2023** [comment]
@puagarwa this issue can be closed as you confirmed us that there is no date for the release yet.

**Comment by RF2023** [comment]
Hello folks, in our latest run we observed a new error which i am attaching below and some tests failed to start on playwright service with the following error. All tests ran on westus3 region. Can you guys please confirm if there was an issue or update that was going on when we ran our tests as our results dropped significantly on this particular run.

<img width="1001" alt="Screenshot 2024-07-04 at 12 06 52 AM" src="https://github.com/microsoft/playwright-testing-service/assets/108815448/c722604b-5fe9-48c7-9731-470b42a23c9c">


Test was skipped due to setup error: There is no session id or trace information attached in the report for this error
<img width="909" alt="Screenshot 2024-07-04 at 12 06 16 AM" src="https://github.com/microsoft/playwright-testing-service/assets/108815448/c6d98faa-7489-408f-8569-c0773c6f2063">

Session ids for tests that failed to start:
1. 03343a27-30e7-4a60-a739-6d3bf6e73c1e
browserContext.newPage
`Error: browserContext.newPage: Test timeout of 300000ms exceeded.`
`Test timeout of 300000ms exceeded while running "beforeEach" hook.`

2. 0724a94a-7522-4683-b07d-d57d3b6dfe49
`browserContext.newPage
Error: browserContext.newPage: Test timeout of 300000ms exceeded.
browserContext.newPage
Test timeout of 300000ms exceeded while setting up "page". `

3. 50b1110b-c06c-4b1b-a477-6b0d3ec63294
`Error: page.goto: Test timeout of 300000ms exceeded.
Call log:
  - navigating to "http://localhost:4000/", waiting until "load"
Error: page.goto: Test timeout of 300000ms exceeded.
Call log:
  - navigating to "http://localhost:4000/", waiting until "load"

    at HomePage.navigateToHomepage (/runner/_work/xxx/xx/xx-test-pw/src/pages/xxpage.ts:24:21)
    at /runner/_work/xx/xx/xx-test-pw/src/tests/xxxx/xx/xxx.test.ts:17:22`
    `Error: page.screenshot: Test timeout of 300000ms exceeded.
Call log:
  - taking page screenshot
  - waiting for fonts to load...
  - fonts loaded`

4. 8d36f12c-6ce9-4d00-b6b7-26ae3e735138
`browserContext.newPage
Error: browserContext.newPage: Test timeout of 300000ms exceeded.
browserContext.newPage
Test timeout of 300000ms exceeded while running "beforeEach" hook.`

5. 96872a93-1ba2-4611-910f-3dcc0a2ee12c
`browserContext.newPage
Error: browserContext.newPage: Test timeout of 300000ms exceeded.
browserContext.newPage
Test timeout of 300000ms exceeded while running "beforeEach" hook.`

6. 51dafd6f-bb50-42f7-b500-6a44381fe239
`browserContext.newPage
Error: browserContext.newPage: Test timeout of 300000ms exceeded.
browserContext.newPage
Test timeout of 300000ms exceeded while running "beforeEach" hook.`

**Comment by puagarwa** [comment]
HI @RF2023, I looked into our telemetry and for all of these connections there wasnt any issue in browser allocation. Enfact the error is also showing that issue came during browserContext.newPage which means browser launch is successful. 

I think the endpoint you are trying to open has some issue and hence its timing out. Can you please check your setup.

Also, i observe in above log you are using [localhost](http://localhost:4000/) , are you using exposeNetwork in servic config ? if yes, only thing need to check is this localhost endpoint is working fine.

**Comment by miguelofbc** [comment]
Hello @puagarwa, thanks for following up! When we run the exact same tests in our infrastructure, everything works as expected. We are only seeing this issue happening while running in ms pw service. The setup is just fine on our end. Could you please further debug on your side? 

Also, we do see a degradation for the last few days on ms pw service? Were there any outage?

**Comment by miguelofbc** [comment]
Hello @puagarwa, this is blocking us at the moment. We are running the exact same setup within our infrastructure and everything works as expected. Could you please take a look?

Some more failures for today's run.

Region -> westus3

SessionIds:
  - 7703a6ff-30ac-40ba-97e5-ca412e263b8d
  - ebdd4001-cb17-42e4-b251-7e7b675a27e4
  - b1440018-f93b-45e3-8bb8-8f74ee0f191e
  - 8f18064e-9be9-4aa0-a7e7-07819e92c16f
  - 2a7f33ab-f83a-438b-b142-5bc1c81304f3

**Comment by puagarwa** [comment]
HI @miguelofbc, I checked your account failure in last 7 days holistically and i dont find many failures due to service infra. The above issue around browserContext.newPage timeout is mostly due to page load issue and we should check your local/public webapp. Can you please enable tracing/snapshot to see why newPage is timing out ? you can also try running it from local machine to easily debug instead of CI.

Also, when you use service mode, where is your endpoint hosted? is it localhost or public endpoint or private endpoint ? 

Also I observe that on June, 02 around 14:30 to 15:00 UTC, there was some timeouts which is due to throttling. Basically there might be more parallel pipelines ran from your side which have exceeded the quota and hence start throttling and hits client timeout. You could raise quota request or increase timeout from service config. But i have only seen this issue on that one instance. 

We can arrange a call with you on current blocker if needed.

**Comment by miguelofbc** [comment]
What would be a good time to arrange that call?

**Comment by puagarwa** [comment]
We are in IST time (+5.5), Monday should be good, depend upon your timezone, we can figure out a time. Please send us an email to [playwrighttesting@microsoft.com](mailto:playwrighttesting@microsoft.com) and we will send you a meeting invite, please mention your timezone or preference.

**Comment by RF2023** [comment]
@miguelofbc thanks for the follow up. @puagarwa please let us know if any information is required from our side. Thank you !

**Comment by vvs11** [comment]
Hi @miguelofbc 
We were able to make some progress in diagnosing this issue. Please allow us some time, we will get back with more info. Thanks

**Comment by puagarwa** [comment]
Hi @miguelofbc, We debugged the issue and able to repro the issue as well. What we found is the issue is happening only for 1.45 and we are working on fixing it. The issue shouldn't happen on 1.44 or earlier versions. 

Meanwhile, i checked our telemetry and found that the above Ids you shared with us are actually 1.45. in-fact, i checked our telemetry and found that from 3rd onward, your account is only using 1.45 without any usage on 1.44. 

As a workaround, I would suggest you downgrade to 1.44 and if you face issue pls share Ids and i will confirm if you are migration to 1.44 is successfully done.

**Comment by puagarwa** [comment]
HI @miguelofbc , @RF2023
   We have further update on the issue, and its good one. We have identified the regression and fixed it. Please confirm from now if you still face browser.newPage timeout issue. 

Just to provide you more info about the issue. in 1.45 there was one regression in playwright framework which was causing the above issue. we have reverted it now https://github.com/microsoft/playwright/pull/31666 and updated our browser fleet with it.

**Comment by miguelofbc** [comment]
Hi @puagarwa,

Thanks for the update. Were you also able to add validation to your release process to prevent this from happening again? This disruption significantly impacted our development process, and we cannot afford similar issues in the future.

**Comment by puagarwa** [comment]
Hi @miguelofbc,
    As part of our issue RCA, we have identified possible test coverage gaps and start working on fixing those immediately. hence we will take care to not cause these regression in future. 

please close the bug if the issue is resolved.

**Comment by hcura-qa** [comment]
Hi @puagarwa,
Unfortunately the issue is not resolved yet.
We are still occasionally getting the `browserType.connect` error, which is being saved by a test retry. Even so, we want to have clean runs, with no retries due to this issue.

Since it is happening on a retry, we don't have the sessionID on the report, however, here is an example of a retry right after a failure due to browserType.connect: `712bb411-fc79-45c6-baa3-9e783d106cec`

Hope your team can analyse and fix it once for all.

Thank you.

**Comment by puagarwa** [comment]
Hi @hcura-qa I looked into our telemetry and found that on average there are 4 failure (out of around 1k) per day for your account which would lead to these test failures at your end, even though failure rate is very low but i can understand that it would cause your test failure on 1st attempt. This is due to same reason i explained earlier https://github.com/microsoft/playwright-testing-service/issues/103#issuecomment-2088391008
    Good part is we have recently worked on this issue and fix will roll out this month which should improve the reliability further.

**Comment by hcura-qa** [comment]
During this morning, we were manually triggering some runs on a small suite.
Facts:
- for about half of the runs, the very first test was failing with `browserType.connect` error
- on the report we can see the error reason as `Timeout 30000ms exceeded`, but on the workflow logs we can see the test failing in some milliseconds (88ms in this case). Even though your team is working on the referred fix, this is a new finding for us.
- I can point to a sessionID right after that failure: `4199c566-dde0-41d2-af25-4877da41fb41`

![image](https://github.com/user-attachments/assets/ab967aec-6f55-4dfc-bf9d-d80ff717d23a)

**Comment by puagarwa** [comment]
Thanks @hcura-qa, Thanks for sharing details. I checked these failures along with all other failures on Friday. 
- these failures have same root cause
- your account have 11 failures in last 7 days and out of these 4 were on Friday.
I will keep you informed about fix deployment.

**Comment by miguelofbc** [comment]
We're experiencing a high number of failures today. Are you facing any outages on your end? Is there a status page where we can check the current service health?
- bfdb9f4c-e590-4f02-b02f-5c3169696112
- e1f9ac3e-3788-40cd-9db1-0e1f955c1ac7
- 127fb613-a73b-492a-affe-da9309bb71b7

**Comment by puagarwa** [comment]
HI @miguelofbc ,
  I checked the above Ids and there is no issue from service side on these Ids. Can you please check trace/video/log for test failure to debug more.

Sharing more detail from these Ids
bfdb9f4c-e590-4f02-b02f-5c3169696112 - active for 420s and then closed normally.
e1f9ac3e-3788-40cd-9db1-0e1f955c1ac7 - active for 420s and then closed normally.
127fb613-a73b-492a-affe-da9309bb71b7 - active for 35s and then closed normally

**Comment by miguelofbc** [comment]
@puagarwa could you please check again? We’re experiencing numerous failures right now. The issue we're seeing is an empty or blank screenshot, along with the following errors:
```Error: page.waitForRequest: Test timeout of 300000ms exceeded.
Error: locator.click: Target page, context or browser has been closed```

- 01ca124f-5530-409d-97e4-776610e1688a

**Comment by puagarwa** [comment]
> 01ca124f-5530-409d-97e4-776610e1688a

@miguelofbc Generally, these issue are related to test or test endpoint. Few things
- is it consistent or transient, if its consistent you can share repro and we can take a look. if not, whats the failure rate ? 
- is it happening for few particular test or for randomly/consistently for all tests ?
- i observe your pw version is 1.45 which rules out any new related regression
- One thing you could do is, try to run it without service to see if issue repro

**Comment by miguelofbc** [comment]
@puagarwa please keep debugging. we disabled the ms pw service for now, but I just tried with latest playwright version (1.47.2) and the problem is also there. 

- 46fdf108-4d65-401f-aa09-a5f8b8da1716
- fd117a8d-ad8c-4076-af8e-c8fa7734c6a4
- 1a15ab04-cc17-416a-9030-2c4e569bcfbb

Without the service, the tests are all passing.

**Comment by puagarwa** [comment]
HI @miguelofbc ,
  We looked into our telemetry and all the sessions you have shared. There isnt anything looking suspicious so far and none of the other customers including our dogfooding have reported any issue. I would need your help in debugging it further.
- How often is it happening, like percentage of failure
- is it happening in particular browser, OS combination ?
- is it random across your suite or any particular suite/tests? , if particular test/suite, please share more details around test for repro.
- Were you able to repro it in CI as well as local laptop run ? 
- Anything which you can share about your test setup
- (optional) if you can write a simple tests which can be shared with us would be very helpful in debugging.

**Comment by miguelofbc** [comment]
Hi @puagarwa, sorry for the delay. This was caused by a race condition within our application, exacerbated by running the Playwright service with 10 worker processes in an infrastructure designed for 4.  The increased concurrency from the excess worker processes magnified the impact of the race condition, leading to a higher rate of failures.

We've implemented a fix to address the race condition in our application and have re-enabled the service.

**Comment by puagarwa** [comment]
HI @miguelofbc ,
  Great to hear things working fine. Let us know if you face any issue.

**Comment by puagarwa** [comment]
HI @miguelofbc , Let me know if we can close this issue.
