### ISSUE TITLE
[BUG]: Report is not shown on runs that are above a number of tests

### ISSUE THREAD

**Issue by seymonyu** [microsoft/playwright-testing-service#155]
**Describe the bug**
When I run .NET tests locally or on pipeline, the report is not shown in some cases.
It happens when the tests are filtered more broad or not filtered. I have tried this filtering with partial namespace, by TestCategory and TestFixture name etc. The results are shown on the command line locally, and the run is shown on MPT service. So I am sure the test ran on the service, with 10 workers. Locally I have the results, pass fail numbers, and logging.

Additionally I tried to filter by category, by adding a new category [Category("UI")] on a couple of classes, which resulted with report. Then I went added that category to every class and ran. No report was shown.

**To Reproduce**
1. Step 1 'Run the tests locally from command line with "dotnet test --logger "microsoft-playwright-testing" -- NUnit.NumberOfTestWorkers=10" command' 
2. Step 2 'View the test run on MPT service'
3. Step 3 'Test run is there but the results are not shown'

**Expected behavior**
I expect the results to be shown when I run the tests. 

**Screenshots**
![Image](https://github.com/user-attachments/assets/36439a18-bb72-4d30-8a8c-3083d2af6b1b)

**Setup information (please complete the following information):**
 - Azure Subscription Id: dfc2b8d2-0b49-4a59-a483-7b6b3a632be1
 - Workspace Name: TAplaywright
 - Service trace Id (if available):
 - Log snippet (if available):
 - Browser on which tests are executed (if applicable):
 - Time range (in PST) when the issue was experienced:
 - Playwright Version:
- Client machine OS: 
- OS requested on Service:

**Additional context**

**Comment by puagarwa** [comment]
HI @seymonyu , We are looking into the issue, will respond to you soon with findings.

**Comment by puagarwa** [comment]
HI @seymonyu , Can you please share console output when you run with our service and publish report. I want to check if you see any warning or error. If there is nothing then probably i will guide you to enable debug logs and share those.

**Comment by seymonyu** [comment]
```

Test Report: https://playwright.microsoft.com/workspaces/westeurope_7559d339-044a-4dce-816f-941bf983cc34/runs/ta-workspace-UI-Chrome%20-%2020241206.2%20-%201

1) The request made to the server is invalid. Please check the request parameters and try again.
Test run completed, flushing telemetry.
Results File: /home/vsts/work/_temp/_fv-az631-210_2024-12-06_08_53_28.trx

Failed!  - Failed:     4, Passed:   217, Skipped:     0, Total:   221, Duration: 14 m 52 s - WorkspaceUITests.dll (net9.0)

##[error]Error: The process '/opt/hostedtoolcache/dotnet/dotnet' failed with exit code 1
Result Attachments will be stored in LogStore
Run Attachments will be stored in LogStore
##[warning].NET 5 has some compatibility issues with older Nuget versions(<=5.7), so if you are using an older Nuget version(and not dotnet cli) to restore, then the dotnet cli commands (e.g. dotnet build) which rely on such restored packages might fail. To mitigate such error, you can either: (1) - Use dotnet cli to restore, (2) - Use Nuget version 5.8 to restore, (3) - Use global.json using an older sdk version(<=3) to build
Info: Azure Pipelines hosted agents have been updated and now contain .Net 5.x SDK/Runtime along with the older .Net Core version which are currently lts. Unless you have locked down a SDK version for your project(s), 5.x SDK might be picked up which might have breaking behavior as compared to previous versions. You can learn more about the breaking changes here: https://docs.microsoft.com/en-us/dotnet/core/tools/ and https://docs.microsoft.com/en-us/dotnet/core/compatibility/ . To learn about more such changes and troubleshoot, refer here: https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/build/dotnet-core-cli?view=azure-devops#troubleshooting
##[error]Dotnet command failed with non-zero exit code on the following projects : [ '/home/vsts/work/1/s/WorkspaceUITests/WorkspaceUITests.csproj' ]
Async Command Start: Publish test results

```

**Comment by puagarwa** [comment]
>> The request made to the server is invalid. Please check the request parameters and try again.


Hi @seymonyu , Yes it seems some issue happened as it apper in console logs here 

I think this output is from CI machine, have you tried it from local machine as well ?

In order to understand the issue further, i would need client side logs which can be enabled via env variable Logging__LogLevel__MicrosoftPlaywrightTesting, value "Info"
Powershell command to set: $env:Logging__LogLevel__MicrosoftPlaywrightTesting="Info"

**Comment by seymonyu** [comment]
This is a part of the log when I add the logger level info

`12/6/2024 1:39:29 PM [Info]: Uploaded buffer to 2310839d-e90b-45fa-a618-13da89d90d76/rawTestResult.json
12/6/2024 1:39:29 PM [Info]: [Informational] Azure-Core: Request [d7dbeb88-1517-42b2-9abe-8a897c271484] PUT https://mtrsprodam1rg1str12.z21.blob.storage.azure.net/33a95qlnsivv2fg9joejwsvwlaw53u92z63wfhoj31ct0tdcxo/902ddfa8-de04-4f12-be5d-ad73e182ae7c/rawTestResult.json?skoid=34e6db75-85bd-4b14-9785-6b4350cf4c95&sktid=33e01921-4d64-4f8c-a055-5bdaffd5e33d&skt=2024-12-06T03%3A34%3A05Z&ske=2024-12-07T03%3A34%3A05Z&sks=b&skv=2023-11-03&sv=2023-11-03&st=2024-12-06T12%3A22%3A45Z&se=2024-12-06T13%3A22%3A45Z&sr=c&sp=racwl&sig=REDACTED
x-ms-blob-type:BlockBlob
x-ms-version:2024-08-04
Accept:application/xml
Content-Length:54
Content-Type:application/octet-stream
x-ms-client-request-id:d7dbeb88-1517-42b2-9abe-8a897c271484
x-ms-return-client-request-id:true
User-Agent:azsdk-net-Storage.Blobs/12.21.1 (.NET 9.0.0; Darwin 24.1.0 Darwin Kernel Version 24.1.0: Thu Oct 10 21:02:45 PDT 2024; root:xnu-11215.41.3~2/RELEASE_ARM64_T8112)
client assembly: Azure.Storage.Blobs
12/6/2024 1:39:29 PM [Info]: [Informational] Azure-Core: Response [d7dbeb88-1517-42b2-9abe-8a897c271484] 201 Created (00.0s)
ETag:"0x8DD15F306E738AB"
Server:Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0
x-ms-request-id:7107098e-201e-0026-47db-474c86000000
x-ms-client-request-id:d7dbeb88-1517-42b2-9abe-8a897c271484
x-ms-version:2024-08-04
x-ms-content-crc64:ursjR3mT9FU=
x-ms-request-server-encrypted:true
Date:Fri, 06 Dec 2024 12:39:28 GMT
Content-Length:0
Content-MD5:tE7inF1Ks1jhGKPb8HCu4w==
Last-Modified:Fri, 06 Dec 2024 12:39:29 GMT

12/6/2024 1:39:29 PM [Info]: Uploaded buffer to 902ddfa8-de04-4f12-be5d-ad73e182ae7c/rawTestResult.json
12/6/2024 1:39:29 PM [Info]: [Informational] Azure-Core: Request [c8b55890-9182-477d-81e2-08f2a577552d] PUT https://mtrsprodam1rg1str12.z21.blob.storage.azure.net/33a95qlnsivv2fg9joejwsvwlaw53u92z63wfhoj31ct0tdcxo/a8c4988d-6603-4c6c-b386-7f506856f542/rawTestResult.json?skoid=34e6db75-85bd-4b14-9785-6b4350cf4c95&sktid=33e01921-4d64-4f8c-a055-5bdaffd5e33d&skt=2024-12-06T03%3A34%3A05Z&ske=2024-12-07T03%3A34%3A05Z&sks=b&skv=2023-11-03&sv=2023-11-03&st=2024-12-06T12%3A22%3A45Z&se=2024-12-06T13%3A22%3A45Z&sr=c&sp=racwl&sig=REDACTED
x-ms-blob-type:BlockBlob
x-ms-version:2024-08-04
Accept:application/xml
Content-Length:54
Content-Type:application/octet-stream
x-ms-client-request-id:c8b55890-9182-477d-81e2-08f2a577552d
x-ms-return-client-request-id:true
User-Agent:azsdk-net-Storage.Blobs/12.21.1 (.NET 9.0.0; Darwin 24.1.0 Darwin Kernel Version 24.1.0: Thu Oct 10 21:02:45 PDT 2024; root:xnu-11215.41.3~2/RELEASE_ARM64_T8112)
client assembly: Azure.Storage.Blobs
12/6/2024 1:39:29 PM [Info]: [Informational] Azure-Core: Response [c8b55890-9182-477d-81e2-08f2a577552d] 201 Created (00.0s)
ETag:"0x8DD15F306EC6805"
Server:Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0
x-ms-request-id:710709a3-201e-0026-59db-474c86000000
x-ms-client-request-id:c8b55890-9182-477d-81e2-08f2a577552d
x-ms-version:2024-08-04
x-ms-content-crc64:ursjR3mT9FU=
x-ms-request-server-encrypted:true
Date:Fri, 06 Dec 2024 12:39:28 GMT
Content-Length:0
Content-MD5:tE7inF1Ks1jhGKPb8HCu4w==
Last-Modified:Fri, 06 Dec 2024 12:39:29 GMT

12/6/2024 1:39:29 PM [Info]: Uploaded buffer to a8c4988d-6603-4c6c-b386-7f506856f542/rawTestResult.json
12/6/2024 1:39:29 PM [Info]: [Informational] Azure-Core: Request [37d70880-f69b-4183-9bb3-c9bc70b9aa0c] PUT https://mtrsprodam1rg1str12.z21.blob.storage.azure.net/33a95qlnsivv2fg9joejwsvwlaw53u92z63wfhoj31ct0tdcxo/9ead1630-e02e-4d31-bfb0-3d7df0177e21/rawTestResult.json?skoid=34e6db75-85bd-4b14-9785-6b4350cf4c95&sktid=33e01921-4d64-4f8c-a055-5bdaffd5e33d&skt=2024-12-06T03%3A34%3A05Z&ske=2024-12-07T03%3A34%3A05Z&sks=b&skv=2023-11-03&sv=2023-11-03&st=2024-12-06T12%3A22%3A45Z&se=2024-12-06T13%3A22%3A45Z&sr=c&sp=racwl&sig=REDACTED
x-ms-blob-type:BlockBlob
x-ms-version:2024-08-04
Accept:application/xml
Content-Length:54
Content-Type:application/octet-stream
x-ms-client-request-id:37d70880-f69b-4183-9bb3-c9bc70b9aa0c
x-ms-return-client-request-id:true
User-Agent:azsdk-net-Storage.Blobs/12.21.1 (.NET 9.0.0; Darwin 24.1.0 Darwin Kernel Version 24.1.0: Thu Oct 10 21:02:45 PDT 2024; root:xnu-11215.41.3~2/RELEASE_ARM64_T8112)
client assembly: Azure.Storage.Blobs
12/6/2024 1:39:29 PM [Info]: [Informational] Azure-Core: Response [37d70880-f69b-4183-9bb3-c9bc70b9aa0c] 201 Created (00.0s)
ETag:"0x8DD15F306F1975D"
Server:Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0
x-ms-request-id:710709bb-201e-0026-6fdb-474c86000000
x-ms-client-request-id:37d70880-f69b-4183-9bb3-c9bc70b9aa0c
x-ms-version:2024-08-04
x-ms-content-crc64:ursjR3mT9FU=
x-ms-request-server-encrypted:true
Date:Fri, 06 Dec 2024 12:39:28 GMT
Content-Length:0
Content-MD5:tE7inF1Ks1jhGKPb8HCu4w==
Last-Modified:Fri, 06 Dec 2024 12:39:29 GMT

12/6/2024 1:39:29 PM [Info]: Uploaded buffer to 9ead1630-e02e-4d31-bfb0-3d7df0177e21/rawTestResult.json
12/6/2024 1:39:29 PM [Info]: [Informational] Azure-Core: Request [523a2787-03d7-4779-8742-ea39fef4c672] PUT https://mtrsprodam1rg1str12.z21.blob.storage.azure.net/33a95qlnsivv2fg9joejwsvwlaw53u92z63wfhoj31ct0tdcxo/e382ec59-e031-41bc-9b03-364cd77ce5c4/rawTestResult.json?skoid=34e6db75-85bd-4b14-9785-6b4350cf4c95&sktid=33e01921-4d64-4f8c-a055-5bdaffd5e33d&skt=2024-12-06T03%3A34%3A05Z&ske=2024-12-07T03%3A34%3A05Z&sks=b&skv=2023-11-03&sv=2023-11-03&st=2024-12-06T12%3A22%3A45Z&se=2024-12-06T13%3A22%3A45Z&sr=c&sp=racwl&sig=REDACTED
x-ms-blob-type:BlockBlob
x-ms-version:2024-08-04
Accept:application/xml
Content-Length:54
Content-Type:application/octet-stream
x-ms-client-request-id:523a2787-03d7-4779-8742-ea39fef4c672
x-ms-return-client-request-id:true
User-Agent:azsdk-net-Storage.Blobs/12.21.1 (.NET 9.0.0; Darwin 24.1.0 Darwin Kernel Version 24.1.0: Thu Oct 10 21:02:45 PDT 2024; root:xnu-11215.41.3~2/RELEASE_ARM64_T8112)
client assembly: Azure.Storage.Blobs
12/6/2024 1:39:29 PM [Info]: [Informational] Azure-Core: Response [523a2787-03d7-4779-8742-ea39fef4c672] 201 Created (00.0s)
ETag:"0x8DD15F306F69FAB"
Server:Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0
x-ms-request-id:710709cc-201e-0026-7edb-474c86000000
x-ms-client-request-id:523a2787-03d7-4779-8742-ea39fef4c672
x-ms-version:2024-08-04
x-ms-content-crc64:ursjR3mT9FU=
x-ms-request-server-encrypted:true
Date:Fri, 06 Dec 2024 12:39:28 GMT
Content-Length:0
Content-MD5:tE7inF1Ks1jhGKPb8HCu4w==
Last-Modified:Fri, 06 Dec 2024 12:39:29 GMT

12/6/2024 1:39:29 PM [Info]: Uploaded buffer to e382ec59-e031-41bc-9b03-364cd77ce5c4/rawTestResult.json
12/6/2024 1:39:29 PM [Info]: [Informational] Azure-Core: Request [feb15c88-9b43-4a20-858e-b23ada812675] PUT https://mtrsprodam1rg1str12.z21.blob.storage.azure.net/33a95qlnsivv2fg9joejwsvwlaw53u92z63wfhoj31ct0tdcxo/787bc0e3-ac73-4c05-89e4-e8807f0bb1e4/rawTestResult.json?skoid=34e6db75-85bd-4b14-9785-6b4350cf4c95&sktid=33e01921-4d64-4f8c-a055-5bdaffd5e33d&skt=2024-12-06T03%3A34%3A05Z&ske=2024-12-07T03%3A34%3A05Z&sks=b&skv=2023-11-03&sv=2023-11-03&st=2024-12-06T12%3A22%3A45Z&se=2024-12-06T13%3A22%3A45Z&sr=c&sp=racwl&sig=REDACTED
x-ms-blob-type:BlockBlob
x-ms-version:2024-08-04
Accept:application/xml
Content-Length:54
Content-Type:application/octet-stream
x-ms-client-request-id:feb15c88-9b43-4a20-858e-b23ada812675
x-ms-return-client-request-id:true
User-Agent:azsdk-net-Storage.Blobs/12.21.1 (.NET 9.0.0; Darwin 24.1.0 Darwin Kernel Version 24.1.0: Thu Oct 10 21:02:45 PDT 2024; root:xnu-11215.41.3~2/RELEASE_ARM64_T8112)
client assembly: Azure.Storage.Blobs
12/6/2024 1:39:29 PM [Info]: [Informational] Azure-Core: Response [feb15c88-9b43-4a20-858e-b23ada812675] 201 Created (00.0s)
ETag:"0x8DD15F306FBA7FE"
Server:Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0
x-ms-request-id:710709ed-201e-0026-1adb-474c86000000
x-ms-client-request-id:feb15c88-9b43-4a20-858e-b23ada812675
x-ms-version:2024-08-04
x-ms-content-crc64:ursjR3mT9FU=
x-ms-request-server-encrypted:true
Date:Fri, 06 Dec 2024 12:39:28 GMT
Content-Length:0
Content-MD5:tE7inF1Ks1jhGKPb8HCu4w==
Last-Modified:Fri, 06 Dec 2024 12:39:29 GMT

12/6/2024 1:39:29 PM [Info]: Uploaded buffer to 787bc0e3-ac73-4c05-89e4-e8807f0bb1e4/rawTestResult.json
12/6/2024 1:39:29 PM [Info]: Successfully uploaded raw test results
12/6/2024 1:39:29 PM [Info]: [Informational] Azure-Core: Request [0b354538-2100-4a36-8be7-04e2eedc8c07] POST https://westeurope.reporting.api.playwright.microsoft.com/workspaces/westeurope_7559d339-044a-4dce-816f-941bf983cc34/test-runs/dba51aa8-ec71-4eb4-9c8c-e2603e3bb5df:updateshardexecutionstatus?api-version=2024-09-01-preview
Accept:application/json
Authorization:REDACTED
x-correlation-id:REDACTED
Content-Type:application/json
x-ms-client-request-id:0b354538-2100-4a36-8be7-04e2eedc8c07
x-ms-return-client-request-id:true
User-Agent:azsdk-net-Developer.MicrosoftPlaywrightTesting.TestLogger/1.0.0-beta.3 (.NET 9.0.0; Darwin 24.1.0 Darwin Kernel Version 24.1.0: Thu Oct 10 21:02:45 PDT 2024; root:xnu-11215.41.3~2/RELEASE_ARM64_T8112)
client assembly: Azure.Developer.MicrosoftPlaywrightTesting.TestLogger
12/6/2024 1:39:30 PM [Info]: [Informational] Azure-Core: Response [0b354538-2100-4a36-8be7-04e2eedc8c07] 200 OK (00.7s)
Date:Fri, 06 Dec 2024 12:39:30 GMT
Transfer-Encoding:chunked
Connection:keep-alive
x-ms-correlation-request-id:REDACTED
x-ms-client-request-id:62fae9ed-52bc-4176-a8fe-ae99f2717c56
x-correlation-id:REDACTED
User-Agent:azsdk-net-Developer.MicrosoftPlaywrightTesting.TestLogger/1.0.0-beta.3 (.NET 9.0.0; Darwin 24.1.0 Darwin Kernel Version 24.1.0: Thu Oct 10 21:02:45 PDT 2024; root:xnu-11215.41.3~2/RELEASE_ARM64_T8112)
mise-correlation-id:REDACTED
api-supported-versions:REDACTED
Strict-Transport-Security:REDACTED
X-Content-Type-Options:REDACTED
Set-Cookie:REDACTED
x-azure-ref:REDACTED
X-Cache:REDACTED
Content-Type:application/json; charset=utf-8

12/6/2024 1:39:30 PM [Info]: Successfully ended test run shard

Test Report: https://playwright.microsoft.com/workspaces/westeurope_7559d339-044a-4dce-816f-941bf983cc34/runs/dba51aa8-ec71-4eb4-9c8c-e2603e3bb5df

1) The request made to the server is invalid. Please check the request parameters and try again.
12/6/2024 1:39:30 PM [Info]: Cleaning up Playwright service resources.
  WorkspaceUITests test failed with 6 error(s) (1037.6s)
    /Users/seymafirat/Repos/ta-workspace/WorkspaceCommon/Helpers/LocatorAssertionHelper.cs(17): error TESTERROR: 
      TC01_AssignAdminAndGuestToFileInList_ShouldResultInFileWithTwoAssignees (16s 3ms): Error Message: Task should have WU as an assignee.:
      Locator expected to be visible 
      Call log:
        -   - LocatorAssertions.ToBeVisibleAsync with timeout 5000ms
        -   - waiting for Locator("vv-task-list-item #wsTaskRow-8022e984-9a4c-49db-915f-7bf80652e915").Locator(".avatar").GetByText("WU")
      Stack Trace:
         at WorkspaceCommon.Helpers.LocatorAssertionHelper.LocatorAssertionAsync(Func`1 methodToExecute, String locatorName) in /Users/seymafirat/Repos/ta-workspace/WorkspaceCommon/Helpers/LocatorAssertionHelper
      .cs:line 17
         at WorkspaceUITests.TestSuites.DataCollectionTestSuites.ManageItemsTestSuite.ManageAssigneesTestSet.TC01_AssignAdminAndGuestToFileInList_ShouldResultInFileWithTwoAssignees() in /Users/seymafirat/Repos/t
      a-workspace/WorkspaceUITests/TestSuites/DataCollectionTestSuites/ManageItemsTestSuite/ManageAssigneesTestSet.cs:line 50
         at NUnit.Framework.Internal.AsyncToSyncAdapter.Await[TResult](Func`1 invoke)
         at NUnit.Framework.Internal.Commands.TestMethodCommand.RunTestMethod(TestExecutionContext context)
         at NUnit.Framework.Internal.Commands.TestMethodCommand.Execute(TestExecutionContext context)
         at NUnit.Framework.Internal.Commands.DelegatingTestCommand.RunTestMethodInThreadAbortSafeZone(TestExecutionContext context, Action action)
      
      1)    at WorkspaceCommon.Helpers.LocatorAssertionHelper.LocatorAssertionAsync(Func`1 methodToExecute, String locatorName) in /Users/seymafirat/Repos/ta-workspace/WorkspaceCommon/Helpers/LocatorAssertionHel
      per.cs:line 13
    /Users/seymafirat/Repos/ta-workspace/WorkspaceCommon/Helpers/JsonDeserializerHelper.cs(9): error TESTERROR: 
      TC02_DeleteFolderThatContainsSubfolders_ShouldDeleteFolderWithSubfoldersItems (44s 369ms): Error Message: System.Net.Http.HttpRequestException : Response status code does not indicate success: 403 (Forbidd
      en).
      Stack Trace:
         at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
         at WorkspaceCommon.Helpers.JsonDeserializerHelper.DeserializeResponse[T](HttpResponseMessage responseMessage) in /Users/seymafirat/Repos/ta-workspace/WorkspaceCommon/Helpers/JsonDeserializerHelper.cs:li
      ne 9
         at WorkspaceCommon.Services.QuestionnaireService.AddTaskToQuestionnaire(String questionnaireId, AddTaskModel addTaskModel, String parentId) in /Users/seymafirat/Repos/ta-workspace/WorkspaceCommon/Servic
      es/QuestionnaireService.cs:line 427
         at WorkspaceCommon.Services.QuestionnaireService.AddFolder(String questionnaireId, String folderName, String parentId) in /Users/seymafirat/Repos/ta-workspace/WorkspaceCommon/Services/QuestionnaireServi
      ce.cs:line 440
         at WorkspaceUITests.TestSuites.DataCollectionTestSuites.ManageItemsTestSuite.DeleteItemTestSet.TC02_DeleteFolderThatContainsSubfolders_ShouldDeleteFolderWithSubfoldersItems() in /Users/seymafirat/Repos/
      ta-workspace/WorkspaceUITests/TestSuites/DataCollectionTestSuites/ManageItemsTestSuite/DeleteItemTestSet.cs:line 51
         at NUnit.Framework.Internal.AsyncToSyncAdapter.Await[TResult](Func`1 invoke)
         at NUnit.Framework.Internal.Commands.TestMethodCommand.Execute(TestExecutionContext context)
         at NUnit.Framework.Internal.Commands.DelegatingTestCommand.RunTestMethodInThreadAbortSafeZone(TestExecutionContext context, Action action)
    /_/src/Playwright/Core/AssertionsBase.cs(87): error TESTERROR: 
      TC01_AdminPermanentlyDeletesTask_ShouldPermanentlyDeleteTask (1m 34s): Error Message: Microsoft.Playwright.PlaywrightException : Locator expected to have text '0'
      But was: '6' 
      Call log:
        -   - LocatorAssertions.ToHaveTextAsync with timeout 5000ms
        -   - waiting for Locator("vv-recycle-bin-toolbar").Locator(".recycle-bin").Locator(".mat-badge-content")
        -     9 × locator resolved to <span aria-hidden="true" id="mat-badge-content-3" class="mat-badge-content mat-badge-active">6</span>
        -       - unexpected value "6"
      Stack Trace:
         at Microsoft.Playwright.Core.AssertionsBase.ExpectImplAsync(String expression, FrameExpectOptions expectOptions, Object expected, String message) in /_/src/Playwright/Core/AssertionsBase.cs:line 87
         at Microsoft.Playwright.Core.AssertionsBase.ExpectImplAsync(String expression, ExpectedTextValue[] expectedText, Object expected, String message, FrameExpectOptions options) in /_/src/Playwright/Core/As
      sertionsBase.cs:line 65
         at Microsoft.Playwright.Core.AssertionsBase.ExpectImplAsync(String expression, ExpectedTextValue textValue, Object expected, String message, FrameExpectOptions options) in /_/src/Playwright/Core/Asserti
      onsBase.cs:line 57
         at WorkspaceUITests.TestSuites.DataCollectionTestSuites.RecycleBinTestSet.TC01_AdminPermanentlyDeletesTask_ShouldPermanentlyDeleteTask() in /Users/seymafirat/Repos/ta-workspace/WorkspaceUITests/TestSuit
      es/DataCollectionTestSuites/RecycleBinTestSet.cs:line 45
         at NUnit.Framework.Internal.AsyncToSyncAdapter.Await[TResult](Func`1 invoke)
         at NUnit.Framework.Internal.Commands.TestMethodCommand.Execute(TestExecutionContext context)
         at NUnit.Framework.Internal.Commands.DelegatingTestCommand.RunTestMethodInThreadAbortSafeZone(TestExecutionContext context, Action action)
    /Users/seymafirat/Repos/ta-workspace/WorkspaceCommon/Helpers/LocatorAssertionHelper.cs(17): error TESTERROR: 
      TC02_GuestWritesChatAndChecksIcon_ShouldPostMessageAndOutlineChatIconBlack (53s 82ms): Error Message: Chat message should have timestamp.:
      Locator expected to be visible 
      Call log:
        -   - LocatorAssertions.ToBeVisibleAsync with timeout 5000ms
        -   - waiting for Locator("mat-dialog-container").Locator(".messages").Locator(".msg").Filter(new() { HasText = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed doeiusmod tempor incididunt u
      t labore et dolore magna aliqua. Utenim ad minim veniam, quis nostrud exercitation ullamco laboris nisiut aliquip ex ea commodo consequat. Duis aute irure dolor inreprehenderit in voluptate velit esse cill
      um dolore eu fugiat nullapariatur. Excepteur sint occaecat cupidatat non proident, sunt inculpa qui officia deserunt mollit anim id est laborum 12/6/2024 1:30:17 PM" }).Locator(".date").Filter(new() { HasT
      ext = "Today at 1:30 PM" })
      Stack Trace:
         at WorkspaceCommon.Helpers.LocatorAssertionHelper.LocatorAssertionAsync(Func`1 methodToExecute, String locatorName) in /Users/seymafirat/Repos/ta-workspace/WorkspaceCommon/Helpers/LocatorAssertionHelper
      .cs:line 17
         at WorkspaceUITests.TestSuites.ItemDetailsTestSuite.ChatTestSet.TC02_GuestWritesChatAndChecksIcon_ShouldPostMessageAndOutlineChatIconBlack() in /Users/seymafirat/Repos/ta-workspace/WorkspaceUITests/Test
      Suites/ItemDetailsTestSuite/ChatTestSet.cs:line 70
         at NUnit.Framework.Internal.AsyncToSyncAdapter.Await[TResult](Func`1 invoke)
         at NUnit.Framework.Internal.Commands.TestMethodCommand.Execute(TestExecutionContext context)
         at NUnit.Framework.Internal.Commands.DelegatingTestCommand.RunTestMethodInThreadAbortSafeZone(TestExecutionContext context, Action action)
      
      1)    at WorkspaceCommon.Helpers.LocatorAssertionHelper.LocatorAssertionAsync(Func`1 methodToExecute, String locatorName) in /Users/seymafirat/Repos/ta-workspace/WorkspaceCommon/Helpers/LocatorAssertionHel
      per.cs:line 13
    /_/src/Playwright/Core/AssertionsBase.cs(85): error TESTERROR: 
      TC04_GuestDeletesTaskInRecycleBin_ShouldDeleteTask (33s 113ms): Error Message: Microsoft.Playwright.PlaywrightException : Locator expected to be visible 
      Call log:
        -   - LocatorAssertions.ToBeVisibleAsync with timeout 5000ms
        -   - waiting for Locator("vv-recycle-bin").Locator("#wsTaskRow-85aa6515-0686-4b1a-a88c-207be17a9f5d")
      Stack Trace:
         at Microsoft.Playwright.Core.AssertionsBase.ExpectImplAsync(String expression, FrameExpectOptions expectOptions, Object expected, String message) in /_/src/Playwright/Core/AssertionsBase.cs:line 85
         at Microsoft.Playwright.Core.AssertionsBase.ExpectImplAsync(String expression, ExpectedTextValue[] expectedText, Object expected, String message, FrameExpectOptions options) in /_/src/Playwright/Core/As
      sertionsBase.cs:line 65
         at WorkspaceUITests.TestSuites.DataCollectionTestSuites.RecycleBinTestSet.TC04_GuestDeletesTaskInRecycleBin_ShouldDeleteTask() in /Users/seymafirat/Repos/ta-workspace/WorkspaceUITests/TestSuites/DataCol
      lectionTestSuites/RecycleBinTestSet.cs:line 118
         at NUnit.Framework.Internal.AsyncToSyncAdapter.Await[TResult](Func`1 invoke)
         at NUnit.Framework.Internal.Commands.TestMethodCommand.Execute(TestExecutionContext context)
         at NUnit.Framework.Internal.Commands.DelegatingTestCommand.RunTestMethodInThreadAbortSafeZone(TestExecutionContext context, Action action)
    /Users/seymafirat/Repos/ta-workspace/WorkspaceUITests/bin/Debug/net9.0/WorkspaceUITests.dll : error TESTERROR: 
      TC09_GuestLogoutAndLoginWithFilterApplied_ShouldStillBeFiltered (1m 25s): Error Message: Multiple failures or warnings in test:
        1) Item: FilterCollectionByReadStatusUnread is not visible, but it shoul be:
      Locator expected to be visible 
      Call log:
        -   - LocatorAssertions.ToBeVisibleAsync with timeout 5000ms
        -   - waiting for Locator("vv-task-list-item").GetByRole(AriaRole.Row, new() { Name = "FilterCollectionByReadStatusUnread" }).Locator(".task-name")
        2) Item: SubfolderUnread is not visible, but it shoul be:
      Locator expected to be visible 
      Call log:
        -   - LocatorAssertions.ToBeVisibleAsync with timeout 5000ms
        -   - waiting for Locator("vv-task-list-item").GetByRole(AriaRole.Row, new() { Name = "SubfolderUnread" }).Locator(".task-name")
      
      Stack Trace:
      
      1)    at WorkspaceCommon.Helpers.LocatorAssertionHelper.LocatorAssertionAsync(Func`1 methodToExecute, String locatorName) in /Users/seymafirat/Repos/ta-workspace/WorkspaceCommon/Helpers/LocatorAssertionHel
      per.cs:line 13
      
      2)    at WorkspaceCommon.Helpers.LocatorAssertionHelper.LocatorAssertionAsync(Func`1 methodToExecute, String locatorName) in /Users/seymafirat/Repos/ta-workspace/WorkspaceCommon/Helpers/LocatorAssertionHel
      per.cs:line 13

Test summary: total: 334, failed: 6, succeeded: 328, skipped: 0, duration: 1037.7s
Build failed with 6 error(s) in 1040.3s`

**Comment by puagarwa** [comment]
@seymonyu Thanks for sharing part of log but this part looks fine, i think error happened in step prior to that, can you share full log, probably capture in file if its long. You can as well send to us @ [playwrighttesting@microsoft.com](mailto:playwrighttesting@microsoft.com)

**Comment by puagarwa** [comment]
@seymonyu We looked into your log but log seems truncated, can you please try again and send complete logs, you can redirect it to txt file > log.txt

**Comment by seymonyu** [comment]
@puagarwa I tried to send the results with a detailed description via email, but I think my email is flagged on your side and it's not delivered because of the attachments. Is there another way which I can share them?

**Comment by puagarwa** [comment]
Issue is debugged and cause was suiteId generated inside package is longer than expected at server side. We will make a fix in package.

**Comment by Sid200026** [comment]
Hi @seymonyu, the fix has been published in the latest release ([1.0.0-beta.4](https://www.nuget.org/packages/Azure.Developer.MicrosoftPlaywrightTesting.NUnit/1.0.0-beta.4)). Closing the issue for now, feel free to reopen if the issue persists.
